In [5]:
#challenge 1
import numpy as np

threedimensionalarray = np.ones((2, 3, 4))

print(threedimensionalarray)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [22]:
# make a list of a bunch of numbers in sorted order (chatgpt) 
import numpy as np

numbers_unordered = [68, 6, 3, 77, 13, 20, 22, 66, 40, 67, 87, 70, 7, 61, 36, 21, 86, 38, 83, 45, 24, 74, 62, 51, 15, 90, 25, 58, 27, 37, 55, 46, 80, 32, 88, 54, 75, 34, 82, 79, 96, 50, 64, 59, 93, 72, 94, 63, 18, 16, 49, 58, 11, 64, 95, 57, 23, 9, 62, 35, 88, 99, 22, 80, 75, 55, 37, 44, 61, 27, 39, 73, 47, 38, 45, 54, 2, 53, 42, 6, 4, 79, 12, 85, 76, 83, 63, 77, 67, 3, 21, 68, 19, 87, 78, 89, 50, 25, 66, 46]
numbers_ordered = np.sort(numbers_unordered)
target_number = 7
length_ordered = len(numbers_ordered)


while len(numbers_ordered) > 1:
    midpoint = int(len(numbers_ordered) / 2)
    if numbers_ordered[midpoint] == target_number:
        print("Position: " + str(midpoint))
        break
    elif numbers_ordered[midpoint] > target_number:
        numbers_ordered = numbers_ordered[:midpoint] # start to half
        print("Number not found")
        if len(numbers_ordered) == 1:
            print("-1")
    elif numbers_ordered[midpoint] < target_number:
        numbers_ordered = numbers_ordered[midpoint:] # half to end
        print("Number not found")
        if len(numbers_ordered) == 1:
            print("-1")

Number not found
Number not found
Number not found
Position: 6


In [24]:
import numpy as np

# check for top half, if not there, set midpoint and check for top half again until 1, 

number_input = input("Enter the numbers in your list, seperated with commas and spaces. Example: 10, 25, 5, 2 \n")
numbers_unordered = [int(x.strip()) for x in number_input.split(',')]
numbers_ordered = np.sort(numbers_unordered)
target_number = int(input("Enter what number you're looking for. \n"))
length_ordered = len(numbers_ordered)
start = int(input("Enter the starting index range. \n"))
end = int(input("Enter the ending index range. \n"))
midpoint = int((start + ((end - start)/2)))

while start != end:
    midpoint = int((start + ((end - start)/2)))
    if numbers_ordered[midpoint] == target_number:
        print("Your ordered list is: " + str(numbers_ordered))
        print("You're done. The ordered index of your number is: " + str(midpoint))
        break
    elif numbers_ordered[midpoint] < target_number:
        print("Number not found")
        start = midpoint + 1
        midpoint = int((start + ((end - start)/2)))
        
    elif numbers_ordered[midpoint] > target_number:
        end = midpoint  - 1
        midpoint = int((start + ((end - start)/2)))
        print("Number not found")

Enter the numbers in your list, seperated with commas and spaces. Example: 10, 25, 5, 2 
10, 75, 51, 48, 83, 78, 18, 93, 86, 85, 95, 68, 16, 32, 37, 38, 82, 2, 43, 29, 7, 20, 60, 4, 31, 35, 28, 39, 63, 1, 6, 34, 89, 96, 66, 97, 69, 26, 81, 50, 98, 87, 57, 55, 17, 80, 74, 67, 27, 56
Enter what number you're looking for. 
87
Enter the starting index range. 
0
Enter the ending index range. 
49
Number not found
Number not found
Your ordered list is: [ 1  2  4  6  7 10 16 17 18 20 26 27 28 29 31 32 34 35 37 38 39 43 48 50
 51 55 56 57 60 63 66 67 68 69 74 75 78 80 81 82 83 85 86 87 89 93 95 96
 97 98]
You're done. The ordered index of your number is: 43


oplpo[o[o[[po[[[po[po[[o[p[[oo[po[o[o[[o[[o[]]]]]]]]]]]]]]]]]]]]]
