# Libraries

**Libraries** in programming languages are collections of prewritten code that users can use to optimize a task.

There are countless libraries created for python, but two common ones used in Machine Learning are **Matplotlib** and **NumPy**. 
NumPy divides the data and manipulates it easily. Matplotlib visualizes data and the machine learning changes.



## NumPy

NumPy introduces many functions that help with large datasets. **NumPy** is a library used to make very powerful arrays. 

Python lists can't be used because in order to apply a function, a loop is needed to go through every value in the list. A NumPy array can increase the value of all the elements at once.

Remember when you were learning about lists? If you wanted to multiply each element by 2 you needed to use a for loop.

For NumPy arrays, however, the elements can all be multiplied by 2 simultaneously. 

Machine learning uses many operations on arrays of data. These data sets often contain thousands of numbers and to iterate through every single value one at a time would be difficult and lengthy. NumPy simplifies all of this.

The code below loads NumPy into your program. 

The NumPy library is renamed to make it quicker to access using the  as  keyword. The code above renames the library to “np;” when calling NumPy in your program, refer to it as "np."

1. Run the cell below to import numpy.

In [ ]:
import numpy as np

2. In the cell below, add code to print out the numpy array called array.

In [2]:
import numpy as np
array = np.array([])

# Add your code here:
print(array)

[]


The empty angled brackets ( [ ] ) represent an empty array. The starting array is going to be empty.

Empty data is kinda boring, so next you'll add some values.

3. Use the cell below to update your array. If you want to add different data you can. 

4. Print the array. 

In [3]:
import numpy as np
array = np.array([1,2,3,4])

# Add your code to print the array here:
print (array)

[1 2 3 4]


### Shape

The size of a NumPy array, also called its shape, is important for some functions you'll use for machine learning.

The shape of a NumPy array reveals how many values are in each dimension of the array.

Knowing the size of data tells you how many different data points exist in the array. With machine learning algorithms, these sizes must be known in order for most of the algorithms to work.

1. Run the cell below to check the shape of your array.

In [4]:
import numpy as np

print(array.shape)

(4,)


This calls the shape property of NumPy arrays and lets you see the size of the array.

After running the code above, the output is  `(4, )` — this means there are four individual values inside the array.

### Multidimensional Arrays


Next, you'll make this a two-dimensional array. 

1. Use the cell below to add a two dimensional array.
2. Add code to print out the shape of the array.

In [5]:
import numpy as np
# Create the 2-d array
twod_array = np.array([[1,2], [3, 4]])

# Add your code to print the shape here:
print(twod_array.shape)

(2, 2)


You've just created an array of arrays! This means your first array value is the array  `[1,2] ` and the second array value is the array  `[3,4]` . 

The size will be ` (2,2)` , which is read as two sets of two values. There are two array values each with two values.

In the previous example, the shape was `(4, )` , which is read as just four array values.

#### Now it's your turn!

Can you create an array that has shape `(3,4)`? 

In [13]:
import numpy as np
my_array = np.array([[1, 2, 3, 4], [4, 5, 6, 3], [4, 5, 6, 3]])

# Check that the shape is correct
print(my_array.shape == (3,4))

True


### Array Arithmetic

Now that you can create arrays, let's see what you can do with them!

1. Create two lists and fill them with all 5 ones.
2. Run the cell to add the lists together

In [14]:
# Create the lists here
num1 = [1, 1, 1, 1, 1]
num2 = [1, 1, 1, 1, 1]
# Add the lists together
num1+num2

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

You should see 10 ones print out. When adding lists, Python joins them together. 

Rather than extending the list, sometimes you might need to add values in the array together. In the previous example, how would you get the result ` [2, 2, 2, 2, 2]` ?

To accomplish this, you'll need a for loop. You can use a for loop to access each index in the array. To loop through all the values in the array you'll need to use  `len(num1) `.

You'll also need a third new array to hold the new sums. ` arrayName.append(value)  `adds value to the array.

#### Try this! 

Can you create the for loop to add the two lists elements together? 

<details> <summary> Click here for an example </summary>
    
    
```
#a for loop that loops over every value in the loop based on the size of the array
for i in range(len(num1)): 
    #add the sum of the values at the ith position of the  arrays and save them to num3
    num3.append(num1[i] + num2[i]) 
print(num3)
```
    
    </details>

In [24]:
import numpy as np
num1 = [1, 1, 1, 1, 1]
num2 = [1, 1, 1, 1, 1]
# Use this list to hold your solution
num3 = [] 
# Add your code here to add the elements of the list together

for i in range(len(num1)): 
    #add the sum of the values at the ith position of the  arrays and save them to num3
    num3.append(num1[i] + num2[i]) 
print(num3 == [2, 2, 2, 2, 2])

True


### Arithmetic with NumPy Arrays

While this method works, NumPy arrays let you do the same thing in one line.

1. Run the cell to see the same result using numpy arrays.

In [26]:
# Create two numpy arrays
arr1 = np.array([1, 1, 1, 1, 1]) 
arr2 = np.array([1, 1, 1, 1, 1])
# Add them together 
print(arr1 + arr2)

[2 2 2 2 2]


You should see the array printed with values added together. As long as both numpy arrays are the same size, you can add them together this way.

### Try this! 

Can you create two arrays and add them together?



In [27]:
# Add your code here: 
arr1 = np.array([1, 1, 2, 1, 1]) 
arr2 = np.array([1, 1, 1, 1, 1])
# Add them together 
print(arr1 + arr2)


[2 2 3 2 2]


### Other Operations

The same goes for multiplication, division, and subtraction. Replacing the plus sign in the previous example gives you a new answer.

#### Try this! 

1. Repeat your previous example using `*` instead of `+`


In [28]:
# Add your multiplication code here:
arr1 = np.array([1, 1, 2, 1, 1]) 
arr2 = np.array([1, 1, 1, 1, 1])
print (arr1 * arr2)

[1 1 2 1 1]


2. Repeat your previous example using `/` instead of `+`

In [31]:
# Add your division code here:
# Add your multiplication code here:
arr1 = np.array([1, 1, 2, 1, 1]) 
arr2 = np.array([1, 1, 1, 1, 1])
print (arr1 / arr2)

[1. 1. 2. 1. 1.]


3. Repeat your previous example using `-` instead of `+`

In [32]:
# Add your subtraction code here:
# Add your multiplication code here:
arr1 = np.array([1, 1, 2, 1, 1]) 
arr2 = np.array([1, 1, 1, 1, 1])
print (arr1 - arr2)

[0 0 1 0 0]


### Adding a Number to an Array

You can add an individual number to the other values in an array using an addition operator ( + ). 

1. Run the cell below to see it in action.

In [33]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([2, 3, 4, 5, 6])

print(arr1+5)

[ 6  7  8  9 10]


As you can see, you can use the + operator to combine two regular python lists into a single list. Numpy arrays let you use the + operator to add two same-size arrays together, adding each element in matching locations together. Using the + operator with a Numpy array and a single value will add that value to every element in the array.